### ISSUE TITLE
fails at compilation

### ISSUE THREAD

**Issue by pyladune** [OvermindDL1/polymer-brunch#2]
after setting it correctly in deps using 

>  {:"polymer-brunch", git: "https://github.com/OvermindDL1/polymer-brunch.git", only: [:dev, :test]}

and in brunch config ;

>     polymer: {
>       vulcanize: { // A top-level vulcanize is the 'default' path for files that do not match any in 'paths'.
>         options: { // These are normal vulcanize options passed as-is.
>           abspath: "web/static",
>           stripComments: true
>         }
>       },
>       crisper: {  // A top-level crisper is the 'default' path for files that do not match any in 'paths'
>         disabled: false, // If true then the vulcanized file is not split.
>         options: {}, // These are normal crisper options passed as-is.
>       },
>       paths: {
>         // The key is matched to the end of the path, if this file in the key
>         // is being compiled now then the global culvanize and crisper are not
>         // not used at all.  This can also be a regex matcher.
>         "somefile.polymer" : {
>           vulcanize: {} // Specifies vulcanize's options, the global version is unused
>           // If one is undefined, like crisper here, then it has no settings
>           // used, not even the global will be used, this is fully distinct.
>         }
>       }
>       copyPathsToPublic: { // A set of paths to copy.
>         paths: {
>           "bower_components": [ // Place in 'public' to copy to
>             "web/static/assets/bower_components"
>             // List of files to copy from, if this is a directory then copy all
>             // the files in the directory, not the directory itself.
>           ]
>         },
>         // verbosity: If 0 then no logging, if 1 then single line summary, if 2
>         // then summary per directory recursed into, if 3 then each and every
>         // file that is copied is printed.
>         verbosity: 1,
>         // onlyChanged: If true then compares timestamps before copying, this is
>         // only useful when 'watch' is used, it will always copy files
>         // regardless when just doing a normal build.
>         onlyChanged: true
>       }
>     },
> 

Despite Mix.deps.get runs fine. it fails at mix.phoenix.server with 

> 
> Could not compile :"polymer-brunch", no "mix.exs", "rebar.config" or "Makefile" (pass :compile as an option to customize compilation, set it to "false" to do nothing)
> Unchecked dependencies for environment dev:
> * polymer-brunch (https://github.com/OvermindDL1/polymer-brunch.git)
>   could not find an app file at _build/dev/lib/polymer-brunch/ebin/polymer-brunch.app. This may happen if the dependency was not yet compiled, or you specified the wrong application name in your deps, or the dependency indeed has no app file (then you can pass app: false as option)
> ** (Mix) Can't continue due to errors on dependencies

**Comment by OvermindDL1** [comment]
Ah, that is because this is not an Elixir library, but rather a Brunch library.  :-)

In your elixir/phoenix project, open your package.json file, and add this to your devDependencies section to make it look something like this:
```json
  "devDependencies": {
    "polymer-brunch": "github:OvermindDL1/polymer-brunch",
  },
```
Along with any other dependencies you have in devDependencies.  :-)

Feel free to keep asking questions in this issue about any integration issues you have.  I never really documented this as I did not expect anyone else to ever really find it and you asking questions shows me what I'd need to focus on to document it.  ^.^

But as the specific issue is resolved by the above steps, I'll close this, but keep asking integration questions here or open up more issues about other problems.  :-)
